const courses = [
  // {
  //   id: "ertyudgh567vbnm567vbnm",
  //   image:
  //     "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80",
  //   instructor: {
  //     name: "HMK CodeWeb",
  //     picture: "https://randomuser.me/api/portraits/men/32.jpg",
  //   },
  //   avatar: "https://randomuser.me/api/portraits/men/32.jpg",
  //   category: "UI/UX Design",
  //   categoryColor: "bg-green-100 text-green-600",
  //   title: "Data Science and Machine Learning with Python – Hands On!",
  //   duration: "08 hr 15 mins",
  //   lectures: "29 Lectures",
  //   price: "$385.00",
  //   original: "$440.00",
  //   rating: 4.9,
  // },
  {
    id: 2,
    image:
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&q=80",
    instructor: "Pamela Foster",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    category: "Data Science",
    categoryColor: "bg-green-100 text-green-600",
    title: "Create Amazing Color Schemes for Your UX Design Projects",
    duration: "08 hr 15 mins",
    lectures: "29 Lectures",
    price: "$420.00",
    original: null,
    rating: 4.9,
  },
  {
    id: 3,
    image:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80",
    instructor: "Rose Simmons",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    category: "Data Science",
    categoryColor: "bg-green-100 text-green-600",
    title: "Culture & Leadership: Strategies for a Successful Business",
    duration: "08 hr 15 mins",
    lectures: "29 Lectures",
    price: "$295.00",
    original: "$340.00",
    rating: 4.9,
  },
  {
    id: 4,
    image:
      "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&q=80",
    instructor: "Jason Williams",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    category: "Financial",
    categoryColor: "bg-blue-100 text-blue-600",
    title: "Finance Series: Learn to Budget and Calculate your Net Worth.",
    duration: "08 hr 15 mins",
    lectures: "29 Lectures",
    price: "Free",
    original: null,
    rating: 4.9,
    isFree: true,
  },
  {
    id: 5,
    image:
      "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=400&q=80",
    instructor: "Jason Williams",
    avatar: "https://randomuser.me/api/portraits/men/45.jpg",
    category: "Business",
    categoryColor: "bg-orange-100 text-orange-600",
    title: "Build Brand Into Marketing: Tackling the New Marketing Landscape",
    duration: "08 hr 15 mins",
    lectures: "29 Lectures",
    price: "$136.00",
    original: null,
    rating: 4.9,
  },
  {
    id: 6,
    image:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    instructor: "Jason Williams",
    avatar: "https://randomuser.me/api/portraits/women/25.jpg",
    category: "UI/UX Design",
    categoryColor: "bg-purple-100 text-purple-600",
    title:
      "Graphic Design: Illustrating Badges and Icons with Geometric Shapes",
    duration: "08 hr 15 mins",
    lectures: "29 Lectures",
    price: "$237.00",
    original: null,
    rating: 4.9,
  },
];

export default courses;